
name : Publish package to artifactory

on:
  push:
    branches: [ master,main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Tar files
        run: git archive -o latest.tar.gz HEAD
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: latestt.tar.gz
